import React from 'react'
import { Content, Title, TextItalic, Paragraph, Subtitle, Span, Bold, Link } from './TermsAndConditions.elements'
import { Container } from '../../globalStyles' 
const TermsAndConditions = () => {
    return (
        <Container>
        <Content>
            <Title>Terms of Use</Title>
            <TextItalic>Last Updated: April 10, 2022</TextItalic>
            <Paragraph>These Terms of Use (“<Bold>Terms”</Bold>) apply to your access to and use of the www.Remigo.com website, mobile applications, and all other web sites, provided by us with a link to these Terms (collectively the “<Bold>Sites</Bold>”), as well as the products, content, features and services available on or through the Sites (collectively, together with the Sites, the “<Bold>Services</Bold>”) provided by Remigo, Inc. (“<Bold>Remigo</Bold>” or “<Bold>we</Bold>” or “<Bold>us</Bold>”).</Paragraph>
            <Paragraph>BY CLICKING “I ACCEPT” OR BY ACCESSING OR USING OUR SERVICES, YOU AGREE TO BE BOUND BY THESE TERMS AND ALL TERMS INCORPORATED BY REFERENCE. IF YOU DO NOT AGREE TO THESE TERMS IN THEIR ENTIRETY, DO NOT USE OUR SERVICES.</Paragraph>
            <Paragraph>If you are a real estate agent who received access to the Services from your real estate brokerage company, your use is also subject to the agreement between Remigo and the brokerage company (“Broker Agreement”) and in the event of any conflict between these Terms and the Broker Agreement, the Broker Agreement will govern.</Paragraph>
            <Paragraph>We may make changes to these Terms from time to time. If we make changes, we will provide you with notice of such changes, such as by sending an email, providing a notice through our Services or updating the date at the top of these Terms. Unless we say otherwise in our notice, the amended Terms will be effective immediately, and your continued use of our Services after we provide such notice will confirm your acceptance of the changes. If you do not agree to the amended Terms, you must stop using our Services.</Paragraph>
            <Paragraph>If you have any questions about these Terms or our Services, please contact us at <a href="mailto:support@remigo.com"><Span>support@remigo.com</Span></a>.</Paragraph>
            <Paragraph>ONLY USERS WHO ARE 18 YEARS OF AGE OR OLDER ARE AUTHORIZED TO USE THE SERVICES. BY ACCESSING OR USING THE SERVICES, YOU REPRESENT TO Remigo THAT YOU ARE AT LEAST 18 YEARS OLD AND CAN FORM LEGALLY BINDING CONTRACTS UNDER APPLICABLE LAW. IF YOU DO NOT QUALIFY FOR THE SERVICES, PLEASE DO NOT ATTEMPT TO ACCESS OR USE THE SERVICES.</Paragraph>
            <Paragraph>If you use our Services on behalf of another person or entity, (1) all references to “you” throughout these Terms will include that person or entity, (2) you represent that you are authorized to accept these Terms on that person’s or entity’s behalf, and (3) in the event you or the person or entity violates these Terms, the person or entity agrees to be responsible to us.</Paragraph>
            <Subtitle>1. Privacy</Subtitle>
            <Paragraph>
            Please refer to Remigo’s Privacy Policy located at <Link href="https://app.remigo.com/privacy">https://app.remigo.com/privacy</Link> for information on how Remigo collects, uses and discloses personally identifiable information from its users.
            </Paragraph>
            <Subtitle>2. Account Credentials</Subtitle>
            <Paragraph>
            To use certain features of the Services, you may have to register for an account on the Services. If you register for an account, you must provide accurate account information and promptly update this information if it changes. You are responsible for maintaining the confidentiality of your log-in credentials to use the Services and are fully responsible for all activities that occur through the use of your credentials. You will notify Remigo immediately of any unauthorized use of your log-in credentials or any other breach of security with respect to your account. Remigo will not be liable for any loss or damage arising from unauthorized use of your credentials. Remigo reserves the right to terminate your account, or reclaim usernames, (including on behalf of businesses or individuals that hold legal claim, including trademark rights, in those usernames) upon reasonable notice to you.             
            </Paragraph>
            <Subtitle>3. Use of the Services</Subtitle>
            <Paragraph>
            <Bold>License</Bold>. You are granted a limited, non-sublicensable license (“ License”) to access and use the Services solely on the terms and conditions set forth in these Terms. The License does not include (and you are prohibited from): (a) modifying or otherwise making any derivative uses of the Services; (b) use of any data mining, robots or similar data gathering or extraction methods; (c) any reverse engineering, decompiling, disassembling or hacking of any aspect of the Services or any part thereof, or attempting to do any of the foregoing, except and solely to the extent permitted by these Terms; (d) downloading (other than the page caching) of any portion of the Services or any information contained therein, except as expressly permitted by these Terms; or (e) any use of the Services other than for their intended purpose. Any use of the Services other than as specifically authorized herein, without the prior written permission of Remigo, is strictly prohibited and will terminate the License granted herein.
            </Paragraph>
            <Paragraph>
            <Bold>Ownership</Bold>. Except for the licenses granted herein, you acknowledge that you have no right, title or interest in or to the Services, Remigo Marks (as defined below), or any of the Services’ content . Remigo and its licensors own and reserve all right, title, and interest in and to all intellectual property rights embodied in or related to the Services or any of its content, except for Business Customer Information (defined below) and Submitted Data (defined below).
            </Paragraph>
            <Paragraph>
            <Bold>Third-Party Content</Bold>. Remigo may provide information about third-party products, services, activities or events, or allow third parties to make their content and information available on or through the Services, including publicly available government sources or through multiple listing services or otherwise posted, transmitted, distributed or made available by third parties, including other users (collectively the “ <Bold>Third-Party Content</Bold>”). Remigo provides Third-Party Content as a service to those interested in such content. Your dealings or correspondence with third parties and your use of or interaction with any Third-Party Content are solely between you and the third party. Remigo does not approve, endorse, control, or adopt any Third-Party Content and makes no representation or warranties of any kind regarding such Third Party Content, and your access to and use of such Third-Party Content is at your own risk. Issues of data accuracy may be brought to the attention of Remigo by sending feedback but it is likely that such information accuracy cannot be corrected by Remigo and the entity or person that generated the information must be appealed to. For example: incorrect listing information can only be changed by the third-party listing agent under our terms with the various multiple listing services (each an “MLS”) that we use.
            </Paragraph>
            <Paragraph>
            <Bold>Additional Terms</Bold>. The Services may occasionally require that you agree to additional terms to use the Services, including those relating to Third-Party Content. Any terms required by Remigo for use of any portion of the Services offered by Remigo (but not those of any Third-Party Content) will, unless otherwise expressly stated in such terms, supersede these Terms in the event of a conflict only as to the content, functionality or features of the Services with respect to which those terms relate. Such additional terms (if any) (but not those of any Third-Party Content or services) are hereby incorporated into and made a part of these Terms by reference.
            </Paragraph>
            <Paragraph>
            <Bold>Equal Housing Opportunity</Bold>. All real estate advertised herein is subject to the Federal Fair Housing Act , which makes it illegal to advertise “any preference, limitation, or discrimination because of race, color, religion, sex, handicap, familial status, or national origin, or intention to make any such preference, limitation, or discrimination.” All persons are hereby informed that all dwellings advertised are available on an equal opportunity basis. The U.S. Department of Housing and Urban Development (“HUD”) has published guidelines for those who advertise homes for sale. You can report housing discrimination to HUD in a number of ways, including via phone at 1-800-669-7777 or via web form. HUD provides a number of resources for consumers and professionals relating to fair housing. This is a good place to start: <Link href="http://portal.hud.gov/hudportal/HUD?src=/program_offices/fair_housing_equal_opp/FHLaws/yourrights">http://portal.hud.gov/hudportal/HUD?src=/program_offices/fair_housing_equal_opp/FHLaws/yourrights</Link>. State governments and many local governments have similar laws prohibiting discrimination in housing. This excellent resource can help you find local fair housing enforcement agencies around the country: <Link href="http://www.fairhousing.com/index.cfm?method=agency.search">http://www.fairhousing.com/index.cfm?method=agency.search</Link>.
            </Paragraph>
            <Subtitle>4. Fees and Payment</Subtitle>
            <Paragraph>
            <Bold>The following terms apply if you are an independent agent not accessing the Services through a brokerage company:</Bold>
            </Paragraph>
            <Paragraph>
            <Bold>Fees</Bold>. You will pay the applicable fees quoted to you on the Sites when you purchase the Services and any renewals of any of the foregoing (“ Fees”). Except where prohibited by applicable law or as otherwise set forth in this section, all of Fees are nonrefundable.
            </Paragraph>
            <Paragraph>
            <Bold>Payment</Bold>. If you are subject to Fees, you will provide Remigo with current, complete, accurate and authorized payment method information. You authorize Remigo (and its payment processors) to charge your provided payment method for the selected Services. Remigo may bill your payment card: (a) in advance; (b) at the time of purchase; (c) shortly after purchase; or (d) on a recurring basis. If Remigo has not received your payment for Fees due, to bring your account up to date, Remigo may bill you simultaneously for both past due and current Fees. Regardless of your primary place of business, you will pay Fees using U.S. Dollars and you are solely responsible for all currency conversion costs from its local currency into U.S. Dollars. You authorize Remigo to store your payment method(s) and to automatically charge your payment method(s) upon renewal until you cancel in accordance with these Terms. If your primary payment method fails, you authorize Remigo to charge any other payment method you provided. If you fail to provide payment, Remigo may suspend your subscription. You may edit your payment information anytime within your account on the Sites.
            </Paragraph>
            <Paragraph>
            <Bold>Renewal</Bold>. The subscription period for the Services will be as quoted on the Sites when you purchase the Services. The subscription will automatically renew subject to the same Fees and the same duration as the initial subscription terms. Remigo will charge your on-file payment method on the first day of the renewal of the subscription term.
            </Paragraph>
            <Paragraph>
            <Bold>No Refunds</Bold>. All purchases of Services are final, unless prohibited by law or in the event of suspension of Services by Remigo in accordance withSection 15 of these Terms.
            </Paragraph>
            <Subtitle>5. Business Customer Information and Submitted Data</Subtitle>
            <Paragraph>
            <Bold>Business Customer Information</Bold>. In the course of accessing and using the Services, you will submit or give us access to certain electronic data and information related to you and your organization’s business, including data concerning you and your organization’s end customers (collectively, “Business Customer Information”).
            </Paragraph>
            <Paragraph>
            <Bold>License Grant to Business Customer Information</Bold>. You hereby grant Remigo a non-exclusive, royalty-free right to access, use, copy, distribute, perform, display and process Business Customer Information during the term to: (a) provide and improve the Services, including to prevent or address service or technical problems; (b) perform other activities at your direction or request, including processing initiated by you through your use of the Services; or (c) as compelled by law. Subject to the foregoing license, you and the entity you represent (as applicable) retain all right, title and interest in and to all Business Customer Information.
            </Paragraph>
            <Paragraph>
            <Bold>Processing</Bold>. We process Business Customer Information to perform our Services on your behalf. You are the “controller” or “business”, as defined under applicable law, with respect to Business Customer Information. You, on behalf of you and the entity you represent (as applicable), represent, warrant, and covenant that (1) you have the right and obtained all necessary permissions and consents to use and submit the Business Customer Information in connection with our Services, and (2) you have delivered, and will deliver, any notices or disclosures required under applicable law or regulations for us to process Business Customer Information in connection with the Services.
            </Paragraph>
            <Paragraph>
            <Bold>Submitted Data</Bold>. You are solely responsible for all content that you or your entity or any of your Clients provide through the Services, to Remigo, or from Third-Party Services (collectively, “Submitted Data”). You retain ownership of Submitted Data. However, in addition to any other rights granted to Remigo under these Terms, by providing Submitted Data through the Services, you grant Remigo and its licensors and providers all necessary rights and licenses in and to Submitted Data necessary for Remigo to provide you access to and use of the Services and otherwise perform its obligations described in these Terms. You represent and warrant to Remigo that neither Submitted Data nor the use of Submitted Data by Remigo as permitted will: (1) violate these Terms or any applicable laws, rules, or regulations; (2) be libelous, defamatory, obscene, abusive, pornographic, threatening, or an invasion of privacy; (3) constitute an infringement or misappropriation of the intellectual property rights or other rights of any third party; (4) be illegal in any way or advocate illegal activity; (5) be false, misleading, or inaccurate; or (6) be considered junk mail, spam, a part of a pyramid scheme, a disruptive commercial message or disruptive advertisement. Remigo is not responsible or liable for any deletion, correction, destruction, damage, loss, or failure to store or back-up any Submitted Data. You represent and warrant to Remigo that you have all rights, permissions, and consents necessary to grant Remigo each of the foregoing rights set forth in this Section.
            </Paragraph>
            <Paragraph>
            <Bold>Aggregated Data</Bold>. In addition to the above, you hereby grant Remigo a non-exclusive royalty-free license to use the Business Customer Information and/or Submitted Data: in aggregate or de-identified form (the resulting data, “Aggregated Data”) for the purpose of providing, developing, improving, and/or reporting on the Services, for data analytics, to develop new products or services, and/or any other purpose not prohibited by applicable law. You hereby further grant Remigo a non-exclusive, royalty-free, perpetual, irrevocable, transferable license to use, reproduce, distribute, publicly display, publicly perform and create derivative works from the Aggregated Data for Remigo’s business and other purposes, in such a manner that neither you nor any of your end users can be identified from such data.
            </Paragraph>
            <Paragraph>
            <Bold>User Conduct</Bold>. You will not, nor assist others to:
            <li>Attempt to, or harass, abuse, bully, intimidate or harm or advocate or incite harassment, abuse, bullying, intimidation or harm of another person or group, including Remigo employees;</li>
            <li>Upload, post or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes or any other form of solicitation (commercial or otherwise);</li>
            <li>Solicit, collect or attempt to solicit or collect personal information from other users of the Services, or disclose personal information about a third person on the Services or obtained from the Services without the consent of such person;</li>
            <li>Restrict, discourage or inhibit any person from using the Services;</li>
            <li>Gain unauthorized access to the Services, to other users’ accounts, names or personally identifiable information, or to other computers or website connected or linked to the Services;</li>
            <li>Post, transmit or otherwise make available any virus, worm, spyware or any other computer code, file or program that may or is intended to damage or hijack the operation of any hardware, software or telecommunications equipment, or any other aspect of the Services or communications equipment and computers connected to the Services;</li>
            <li>Remove, disable, damage, circumvent or otherwise interfere with any security-related features of the Services, features that prevent or restrict the use or copying of any part of the Services or any content on the Services, or features that enforce limitations on the use of the Services or any content on the Services;</li>
            <li>Use any scraper, spider, cheats, exploits, robots or other automated means of any kind to access, modify or interfere with the Services, or harvest or manipulate data, except and solely to the extent permitted by these Terms and the features of the Services, deep-link to any feature or content on the Services, bypass any robot exclusion headers or other measures we may use to prevent or restrict access to the Services;</li>
            <li>Crawl, scrape or download any property or other data for inclusion in another real estate search service, content aggregator, or for any other purpose not expressly permitted by these Terms;</li>
            <li>Interfere with or disrupt the Services, networks or servers connected to the Services or violate the regulations, policies or procedures of such networks or servers;</li>
            <li>Post any content or material that promotes or endorses false or misleading information or illegal activities, or endorses or provides instructional information about illegal activities or other activities prohibited by these Terms; </li>
            <li>Engage in any activities in connection with the Services that violate any applicable law, rule or regulation.</li>
            <li>Enforcement of Rules. Enforcement of conduct rules set forth in these Terms is solely at Remigo’s discretion, and failure to enforce such rules in some instances does not constitute a waiver of our right to enforce such rules in other instances. In addition, these rules do not create any private right of action on the part of any third party or any reasonable expectation that the Services will not contain any content or conduct that is prohibited by such rules.</li>
            </Paragraph>
            <Subtitle>6. Intellectual Property Rights</Subtitle>
            <Paragraph>
            <Bold>Generally</Bold>. The Services and content made available on or through the Services, including without limitation, any text, software, graphics, designs, photos, sounds, music, videos and logos, is owned by Remigo, third party licensors of Remigo or users of the Services. Except as explicitly stated in these Terms, all rights in and to the Services, and any content available on or through the Services , and any intellectual property rights embodied or related to the Services or any content, are reserved by us or our licensors. Except as explicitly permitted on the Services, the Services and material made available on the Services may not be copied, reproduced, republished, uploaded, posted, transmitted, modified, or distributed in any way without written permission of the owner.            
            </Paragraph>
            <Paragraph>
            <Bold>Trademarks</Bold>. Remigo, the Remigo logo and any other Remigo product or service names, logos or slogans contained or used in connection with the Services (“Remigo Marks”) are trademarks or service marks of Remigo and may not be copied, imitated or used, in whole or in part, except as provided for in these Terms. All other trademarks, registered trademarks, product names and company names or logos mentioned in the Services are the property of their respective owners. Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof by us.
            </Paragraph>
            <Paragraph>
            <Bold>Trademark License</Bold>. Subject to your continuing compliance with your obligations under these Terms, Remigo hereby grants you a non-exclusive, limited, right during the term of these Terms to display the Remigo Marks, solely in connection with your right to market the Services to and train your Clients. You will immediately change or discontinue any use of any Remigo Marks as requested by Remigo. Remigo has the right, at all reasonable times, to inspect the manner in which you use the Remigo Marks and the quality of any goods and services associated therewith. You will not use any Remigo Marks in a way that implies you are an employee, branch, or affiliate of Remigo, or in an entity name. You will not take or encourage any action during or after the term of these Terms that will in any way impair the rights of Remigo in and to the Remigo Marks or the goodwill inherent therein. Your use of the Remigo Marks and all goodwill therein inures solely to the benefit of Remigo.
            </Paragraph>
            <Paragraph>
            <Bold>Feedback</Bold>. You agree that Remigo shall acquire, and you hereby assign and otherwise transfer to Remigo, any and all right, title, and interest in and to any actual or suggested modifications, design changes, improvements, and other information regarding the features and performance of the Services (“Feedback”), without the payment of additional consideration.
            </Paragraph>
            <Subtitle>7. Service Security</Subtitle>
            <Paragraph>
            You are prohibited from violating, or attempting to violate, the security of the Services. Any such violations may result in criminal and/or civil penalties against you, as well as the termination of your privilege to use the Services, at Remigo’s sole discretion. Remigo reserves the right to investigate any alleged or suspected violations and, if a criminal violation is suspected, refer such suspected violation to the appropriate law enforcement agencies and cooperate fully with such investigations, including, but not limited to, the disclosure of any or all of your activities on or related to the Services.
            </Paragraph>
            <Subtitle>8. Indemnity</Subtitle>
            <Paragraph>
            To the fullest extent permitted by applicable law, You will indemnify, defend, and hold harmless Remigo and our subsidiaries and affiliates, and each of our respective officers, directors, agents, partners, employees agents, contractors, suppliers and licensors (the “<Bold>Remigo Parties</Bold>”), from and against any losses, claims, demands, suits, damages, liabilities, costs and expenses (“<Bold>Claims</Bold>”) arising out of or related to: (a) your access to or use of the Services; (b) Submitted Data, Business Customer Information, or Feedback; (c) your violation of these Terms; or (d) your conduct in connection with the Services, including your violation of the rights of any other person or entity. You agree to promptly notify Remigo Parties of any third-party Claims, cooperate with Remigo Parties in defending such Claims and pay all fees, costs and expenses associated with defending such Claims (including, but not limited to, attorneys’ fees). You also agree that the Remigo Parties will have control of the defense or settlement, at Remigo’s sole option, of any third-party Claims. This indemnity is in addition to, and not in lieu of, any other indemnities set forth in a written agreement between you and Remigo or the other Remigo Parties.
            </Paragraph>
            <Subtitle>9. Disclaimers</Subtitle>
            <Paragraph>
            <li>THE SERVICES AND THE THIRD-PARTY CONTENT ARE PROVIDED AND MADE AVAILABLE ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL FAULTS” BASIS WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY OR OTHERWISE. WITHOUT LIMITING THE FOREGOING, REMIGO IS NOT RESPONSIBLE FOR TYPOGRAPHICAL OR OTHER ERRORS OR OMISSIONS IN LISTINGS OR AGENT INFORMATION INCLUDING RELATING TO PRICING, TEXT OR PHOTOGRAPHY.</li>
            <li>TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, THE REMIGO PARTIES HEREBY DISCLAIM ALL EXPRESS, IMPLIED AND STATUTORY WARRANTIES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT WITH RESPECT TO THE SERVICES AND THE THIRD-PARTY CONTENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU THROUGH THE SERVICES OR FROM Remigo, OR AN EMPLOYEE OR REPRESENTATIVE OF REMIGO, WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. THE REMIGO PARTIES DO NOT WARRANT THAT THE SERVICES OR ANY PART THEREOF, OR ANY FEATURES OR CONTENT OFFERED ON THE SERVICES, WILL BE UNINTERRUPTED OR FREE OF ERRORS, VIRUSES OR OTHER HARMFUL COMPONENTS, AND THEY DO NOT WARRANT THAT ANY OF THE FOREGOING WILL BE CORRECTED. YOU UNDERSTAND AND AGREE THAT YOU USE, ACCESS, DOWNLOAD, OR OTHERWISE OBTAIN INFORMATION, MATERIALS, OR DATA THROUGH THE SERVICES OR ANY ASSOCIATED SERVICES OR APPLICATIONS AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING WITHOUT LIMITATION YOUR COMPUTER SYSTEM USED IN CONNECTION WITH THE SERVICES) OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OR USE OF SUCH MATERIAL OR DATA.</li>
            </Paragraph>
            <Subtitle>10. Limitiation of Liability</Subtitle>
            <Paragraph>
            IN NO EVENT WILL THE REMIGO PARTIES BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR OTHER CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH: (A) THE SERVICES AND THE USE, ACCESS OF OR INABILITY TO USE OR ACCESS THE SERVICES; (B) ANY THIRD-PARTY CONTENT; (C) ANY INCENTIVES OFFERED BY THIRD PARTIES THROUGH THE SERVICES; OR (D) SUBMITTED DATA OR BUSINESS CUSTOMER INFORMATION MADE AVAILABLE THROUGH THE SERVICES, OR ANY LOST PROFITS, BUSINESS INTERRUPTION, OR OTHERWISE, WHETHER BASED IN TORT, CONTRACT OR OTHER LEGAL THEORY, EVEN IF ANY REMIGO PARTY IS EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IF YOU ARE AN INDEPENDENT AGENT, IN NO EVENT WILL THE REMIGO PARTIES BE LIABLE IN THE AGGREGATE FOR ANY DAMAGES INCURRED BY YOU THAT EXCEED THE AMOUNT OF FEES YOU HAVE PAID Remigo TO USE THE SERVICES IN THE 12 MONTHS IMMEDIATELY PRECEDING THE FIRST CLAIM UNDER THESE TERMS. The limitations set forth in thisSection 10 will not limit or exclude liability for the gross negligence, fraud or intentional misconduct of Remigo or the other Remigo Parties or for any other matters in which liability cannot be excluded or limited under applicable law. Additionally, some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitations or exclusions may not apply to you.
            </Paragraph>
            <Subtitle>11. Release</Subtitle>
            <Paragraph>
            To the fullest extent permitted by applicable law, you release Remigo from responsibility, liability, claims, demands and/or damages (actual and consequential) of every kind and nature, known and unknown (including claims of negligence), arising out of or related to disputes between Users and the acts or omissions of third parties. If you are a consumer who resides in California, you hereby waive your rights under California Civil Code § 1542, which provides: “A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which if known by him or her must have materially affected his or her settlement with the debtor.”
            </Paragraph>
            <Subtitle>12. Term of Termination</Subtitle>
            <Paragraph>
            <Bold>Term</Bold>. These Terms will be effective commencing with your first use or registration on the Services and will remain in full force and effect throughout your use of the Services. If you are subject to Fees, the Services will remain in effect for the initial term specified in your subscription terms and will automatically renew for consecutive terms of the same duration as the initial subscription term and subject to the same Fees paid during the initial term, unless the subscription is canceled by you or Remigo prior to any renewal of the subscription.
            </Paragraph>     
            <Paragraph>
            <Bold>Termination by Remigo</Bold>. Remigo may only terminate your subscription, including your account and your use of the Services, if you breach these Terms or the Broker Agreement, as applicable. If your use of the Services is terminated pursuant to these Terms, you will not attempt to use the Services under any name, real or assumed, and further agree that if you violate this restriction after being terminated, you will indemnify and hold us harmless from any and all liability that we may incur therefor.
            </Paragraph>  
            <Paragraph>
            <Bold>Termination by You</Bold>; No Refunds. You may terminate your use of the Services at any time by ceasing use of the Services. If you wish to terminate your account, you may do so by sending an e-mail to info@Remigo.com or using any other account termination functionality that may be offered on or through the Services. For the avoidance of doubt, if you are an independent agent subject to Fees, if you terminate the Services during a subscription period, you will not be entitled to any refund of Fees paid for such subscription period.
            </Paragraph> 
            <Subtitle>13. Jurisdictional Issues</Subtitle>
            <Paragraph>
            The Sites are controlled and operated by Remigo from its offices within the State of California. Those who choose to access or use the Services from other locations, including from outside the United States of America, do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable. Access to the Sites from jurisdictions where the contents or practices of the Services are illegal, unauthorized or penalized is strictly prohibited.
            </Paragraph>  
            <Subtitle>14. Governing Law; Venue</Subtitle>
            <Paragraph>
            The Agreement is governed by and construed in accordance with the laws of the State of California, excluding its conflicts of law rules and without regard to the United Nations Conventions on Contracts for the International Sale of Goods. Any dispute arising from or relating to the subject matter of this Agreement shall be finally settled by arbitration in San Francisco County, California.
            </Paragraph> 
            <Subtitle>15. Miscellaneous</Subtitle>
            <Paragraph>
            <Bold>Evolving Nature of the Services</Bold>. The Services are subject to change at any time. Remigo reserves the right, at its sole discretion, to terminate, suspend, make changes to or modify the Services and its features and functionality, without notice. We continually strive to improve the Services but if you are at any time dissatisfied with the Services, then your sole remedy is to discontinue use of the Services. We do want to hear from our users so do not hesitate to send us an email at info@Remigo.com to let us know what you think.
            </Paragraph>
            <Paragraph>
            <Bold>Waiver</Bold>. A provision of these Terms may be waived only by a written instrument executed by the party entitled to the benefit of such provision. The failure of Remigo to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision.
            </Paragraph> 
            <Paragraph>
            <Bold>Severability</Bold>. If any provision of these Terms shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.
            </Paragraph> 
            <Paragraph>
            <Bold>Assignment</Bold>. These Terms, and any rights and obligations granted hereunder, may not be transferred or assigned by you without the prior written consent of Remigo, but may be assigned by Remigo without restriction. Any assignment attempted to be made by you in violation of these Terms shall be void. These Terms will be binding upon and inure to the benefit of the parties hereto and permitted successors and assigns.
            </Paragraph> 
            <Paragraph>
            <Bold>No Agency</Bold>. You agree that no joint venture, partnership, employment, or agency relationship exists between you and Remigo as a result of these Terms of Use of the Site. You further acknowledge that by submitting Submitted Data or Business Customer Information, no confidential, fiduciary, contractually implied or other relationship is created between you and Remigo other than pursuant to these Terms.
            </Paragraph> 
            <Paragraph>
            <Bold>Survival</Bold>. Sections 1, 2,3,5,6,7,8,9,10,11,12,13,14,15,16, and 17 will survive any expiration or termination of these Terms.
            </Paragraph> 
            <Paragraph>
            <Bold>Headings</Bold>. The heading references herein are for convenience purposes only, do not constitute a part of these Terms, and shall not be deemed to limit or affect any of the provisions hereof.
            </Paragraph> 
            <Paragraph>
            <Bold>Disclosures</Bold>. The Site is offered by Remigo, Inc. located at Remigo, Inc., You may contact us by sending correspondence to the foregoing address or by emailing us at info@Remigo.com. If you are a California resident, you may have these Terms mailed to you electronically by sending a letter to the foregoing address with your electronic mail address and a request for these Terms.
            </Paragraph>  
            <Subtitle>16. Copyright Infringement</Subtitle>
            <Paragraph>
            The Digital Millennium Copyright Act of 1998 (the “DMCA”) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe in good faith that materials available on the Sites infringe your copyright, you (or your agent) may send to Remigo a written notice by mail or e-mail, requesting that Remigo remove such material or block access to it. If you believe in good faith that someone has wrongly filed a notice of copyright infringement against you, the DMCA permits you to send to Remigo a counter-notice. Notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA. See <Link href="http://www.copyright.gov/">http://www.copyright.gov/</Link> for details. Notices and counter-notices must be sent in writing to Remigo’s registered agent as follows: By e-mail to <a href="mailto:support@remigo.com"><Span>support@remigo.com</Span></a>.             
            </Paragraph>
            <Subtitle>17. MLS Terms, Disclosures, and Disclaimers</Subtitle>
            <Paragraph>
            Information about individual properties is provided by many listing sources, including one or more multiple listing services. Listing information is deemed reliable but not guaranteed. By using the Site, you agree to the following terms and conditions:
            <li>You acknowledge that the individual multiple listing service (MLS), which supplies the listing data, owns such data and you acknowledge the ownership and validity of that MLS’s copyright to such data;</li>
            <li>Information provided through the Site may be used only for personal, non-commercial use and only use by a viewer with a bona fide interest in the purchase, sale or lease of real estate of the type being offered via the Site or other electronic means; and</li>
            <li>The viewer will not copy, redistribute or retransmit any of the data or information provided.</li>
            </Paragraph>
            <Paragraph>The following disclaimers apply to listings only from that particular data source:</Paragraph>
            <Paragraph><Bold>Austin MLS (ACTRIS)</Bold> Information provided from the Austin Board of REALTORS® / ACTRIS All information provided is deemed reliable but is not guaranteed and should be independently verified. The Austin Board of REALTORS®, ACTRIS and their affiliates provide the MLS and all content therein “AS IS” and without any warranty, express or implied. IDX information is provided exclusively for consumers’ personal, non-commercial use, and it may not be used for any purpose other than to identify prospective properties consumers may be interested in purchasing. Data is deemed reliable but is not guaranteed accurate by the MLS. <a href="https://trec.texas.gov/forms/consumer-protection-notice"><Span>Texas Real Estate Commission Consumer Protection Notice</Span></a></Paragraph>
        </Content>
        </Container>
    )
}

export default TermsAndConditions
