name: Gatsby Publish

on:
  push:
    branches:
      - gatsby2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          working-directory: client
      - run: touch CNAME
      - run: echo 'www.remigo.com' > CNAME
